/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import model.entidades.Historial;
import model.entidades.HistorialEspecifico;
import model.entidades.Usuario;

/**
 *
 * @author aylee
 */
public class HistorialView extends javax.swing.JFrame {

    /**
     * Creates new form HistorialView
     */
    private static HistorialEspecifico historial;
    
    public HistorialView(HistorialEspecifico historial) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.historial = historial;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        mostrarDatos();
        
    }
    private void mostrarDatos() {
        txtDocumento.setText(historial.getNumeroDocumento());
        txtNombre.setText(historial.getNombreDueño());
        txtApellido.setText(historial.getApellido());
        txtTelefono5.setText(historial.getTelefono());
        txtVeterinario.setText(historial.getVeterinario());
        txtFecha.setText(historial.getFechaConsulta().toString());
        txtMascota.setText(historial.getNombreMascota());
        txtGenero.setText(historial.getGeneroMascota());
        txtTipoMascota.setText(historial.getTipo());
        txtEdadMascota.setText(String.valueOf(historial.getEdad()));
        txtMotivo.setText(historial.getMotivoConsulta());
        txtDiagnostico.setText(historial.getDiagnostico());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtMascota = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiagnostico = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtMotivo = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        txtVeterinario = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        txtTipoMascota = new javax.swing.JTextField();
        txtEdadMascota = new javax.swing.JTextField();
        txtTelefono5 = new javax.swing.JTextField();
        txtTelefono6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GG.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel16.setText("Nro de identificacion:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 210, -1));

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 3, 50)); // NOI18N
        jLabel14.setText("Historial medico");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        txtDocumento.setEditable(false);
        txtDocumento.setBackground(new java.awt.Color(255, 255, 255));
        txtDocumento.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel1.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 220, 30));

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel15.setText("Nombre del dueño:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 220, 30));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel11.setText("Apellido del dueño:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        txtApellido.setEditable(false);
        txtApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtApellido.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 297, 220, 30));

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel20.setText("Nro de telefono:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        txtFecha.setEditable(false);
        txtFecha.setBackground(new java.awt.Color(255, 255, 255));
        txtFecha.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 240, 30));

        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel19.setText("Veterinario");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel21.setText("Fecha de la consulta:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel18.setText("Nombre de la mascota:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        txtMascota.setEditable(false);
        txtMascota.setBackground(new java.awt.Color(255, 255, 255));
        txtMascota.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel1.add(txtMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 240, 30));

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel17.setText("Genero de la mascota:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel27.setText("Tipo de mascota:");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel25.setText("Edad de la mascota:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        txtDiagnostico.setEditable(false);
        txtDiagnostico.setColumns(20);
        txtDiagnostico.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtDiagnostico.setRows(5);
        jScrollPane1.setViewportView(txtDiagnostico);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 460, 190));

        jLabel23.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel23.setText("Diagnostico y tratamiento:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, -1, -1));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        txtMotivo.setEditable(false);
        txtMotivo.setColumns(20);
        txtMotivo.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtMotivo.setRows(5);
        jScrollPane4.setViewportView(txtMotivo);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 460, 140));

        jLabel22.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel22.setText("Motivo de la consulta:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 220, -1));

        txtVeterinario.setEditable(false);
        txtVeterinario.setBackground(new java.awt.Color(255, 255, 255));
        txtVeterinario.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel1.add(txtVeterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 220, 30));

        txtGenero.setEditable(false);
        txtGenero.setBackground(new java.awt.Color(255, 255, 255));
        txtGenero.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel1.add(txtGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 230, 30));

        txtTipoMascota.setEditable(false);
        txtTipoMascota.setBackground(new java.awt.Color(255, 255, 255));
        txtTipoMascota.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel1.add(txtTipoMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 230, 30));

        txtEdadMascota.setEditable(false);
        txtEdadMascota.setBackground(new java.awt.Color(255, 255, 255));
        txtEdadMascota.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel1.add(txtEdadMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 230, 30));

        txtTelefono5.setEditable(false);
        txtTelefono5.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefono5.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel1.add(txtTelefono5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 220, 30));

        txtTelefono6.setEditable(false);
        txtTelefono6.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefono6.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel1.add(txtTelefono6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 220, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GG.jpg"))); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 10, 340, 530));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GG2.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 240, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistorialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistorialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistorialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistorialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistorialView(historial).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextArea txtDiagnostico;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtEdadMascota;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtMascota;
    private javax.swing.JTextArea txtMotivo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono5;
    private javax.swing.JTextField txtTelefono6;
    private javax.swing.JTextField txtTipoMascota;
    private javax.swing.JTextField txtVeterinario;
    // End of variables declaration//GEN-END:variables
}
